### PR TITLE
fix(ci): Replaces the command used to test CUDA 11.1 in the CI.

### PR DESCRIPTION
**Pull request by pdroalves**
### Description
We should be using `cargo xtask test_cuda` for that.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by pdroalves** [comment]
@slab-ci cpu_test

**Comment by pdroalves** [comment]
@slab-ci gpu_test

**Review by agnesLeroy — APPROVED** [review]

**Comment by agnesLeroy** [comment]
@pdroalves there was a dpulicate launch of doc tests in concrete-tasks, is this now fixed? If not we could make the change in this PR I think.

**Comment by pdroalves** [comment]
> @pdroalves there was a dpulicate launch of doc tests in concrete-tasks, is this now fixed? If not we could make the change in this PR I think.

Those in https://github.com/zama-ai/concrete-core/blob/main/concrete-tasks/src/test.rs? I think that is already merged.

**Pull request merged**
