### PR TITLE
Update the CI to test concrete-cuda for two different toolkits

### PR DESCRIPTION
**Pull request by pdroalves**
### Description
In order to support stream-ordered memory allocation and test the cases when it is supported or not, the CI needs to be able to run tests with both toolkit versions.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by pdroalves** [comment]
@slab-ci cpu_test

**Comment by pdroalves** [comment]
@slab-ci gpu_test

**Comment by agnesLeroy** [comment]
@pdroalves I guess we have to merge https://github.com/zama-ai/concrete-core/pull/214 first, then re-launch the tests?

**Comment by pdroalves** [comment]
Ops, exactly. We need #214 first.

**Comment by soonum** [comment]
Maybe  @pdroalves you could integrate the changes I've requested in #214 . It makes more sense I think since you're updating the Action file here.

**Comment by pdroalves** [comment]
Indeed! I will close this PR and push my commit there. Thanks @soonum :-)

**Pull request closed without merging**
