### PR TITLE
Test CI bot release in prodcution

### PR DESCRIPTION
**Pull request by soonum**
### Description

This PR is not meant to be merge in the end. This is just to manually test Slab, Zama's CI bot, features in a production environment.

### CODE REVIEW

**Comment by soonum** [comment]
@slab cpu_tests

**Comment by soonum** [comment]
@slab fake_command

**Comment by soonum** [comment]
@slab-ci fake_command

**Comment by soonum** [comment]
@slab-ci cpu_tests --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by benjamin1555** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by benjamin1555** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by IceTDrinker** [comment]
> Failed to execute command, @soonum is not part of Zama organisation

O_O

**Comment by soonum** [comment]
Yes I'm also surprised of this error...

**Comment by soonum** [comment]
Is it fixed ? Let's see
@slab-ci cpu_test --profile fake_profile

**Comment by IceTDrinker** [comment]
The error does not make much sense, plus it did not happen before, is it really your membership that is being tested ?

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by IceTDrinker** [comment]
welp you've got a bug on your hands 😅

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
@slab-ci cpu_test --profile fake_profile

**Comment by soonum** [comment]
Ok ! Cool It was just a permission problem. You know @IceTDrinker, when you enable permission as orga owner but you still have to validate the change afterward.... that was the problem.

**Comment by IceTDrinker** [comment]
@soonum welcome to the madness 😄

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci fake_command

**Comment by soonum** [comment]
@slab-ci fake_command

**Comment by soonum** [comment]
@slab-ci cpu_test --region us-east-1 --image-id ami-0df0337664ad627fe --instance-type p3.2xlarge --workflow-filename aws_tests.yaml

**Comment by soonum** [comment]
@slab-ci cpu_test --region us-east-1 --image-id ami-0df0337664ad627fe --instance-type m6a.metal --workflow-filename aws_tests.yaml

**Comment by soonum** [comment]
@slab-ci fake_co;;and

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci gpu_test

**Comment by soonum** [comment]
@slab-ci cpu_test -w action_creation.yml -c action_debug_(slab) -i ami-000311d202e281658 -r eu-west-3 -t t3.xlarge

**Comment by soonum** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
@soonum do we keep this PR ?

**Comment by soonum** [comment]
Indeed, we can close this PR. It's not relevant anymore.

**Pull request closed without merging**
