### PR TITLE
chore(core): update READMEs

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Resolves:

closes https://github.com/zama-ai/concrete-core-internal/issues/160

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
~~* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~~
~~* [ ] The draft release description has been updated~~
~~* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~~

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
Note that I'm unsure of the parameters for the example in the concrete-core README.md, I tried to use some of the V0 parameters but it does not seem right as the check at the end is failing on a regular basis.

Should I ping Sam or someone else more specialized in these questions ?

**Review by agnesLeroy — APPROVED** [review]
Thank you @IceTDrinker! Let's leave the parameters as they are for now, they look good to me.

**Comment by IceTDrinker** [comment]
> Thank you @IceTDrinker! Let's leave the parameters as they are for now, they look good to me.

ok but the assert_eq is not working always 😅

**Comment by agnesLeroy** [comment]
> > Thank you @IceTDrinker! Let's leave the parameters as they are for now, they look good to me.
> 
> ok but the assert_eq is not working always sweat_smile

Oh it's because you need to round after calling decrypt.

**Pull request merged**
