### PR TITLE
chore(tasks): make tasks usable on M1 macs

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Resolves:

closes https://github.com/zama-ai/concrete-core-internal/issues/219

### Description

Add a uname call and some small parsing to be able to determine the CPU on mac OS.

The uname call is required to be able to work no matter the toolchain used on mac OS as we encourage devs to override it.

I have an alternative version of this PR where we don't crash if we fail to get infos on mac OS, here we stop if encounter an error.

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
~~* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~~
~~* [ ] The draft release description has been updated~~
~~* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~~

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
cc @bencrts

**Comment by bencrts** [comment]
works on my side!

**Comment by IceTDrinker** [comment]
clippy failure was linked to the updated clap dependency which deprecated more of the old API

**Review by agnesLeroy — APPROVED** [review]
Thanks a lot @IceTDrinker, this will change @bencrts's life :smiley:

**Pull request merged**
