### PR TITLE
fix(csprng): update CPU feature detection

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Resolves:

closes https://github.com/zama-ai/concrete-core-internal/issues/217

### Description

- rdseed is not required for the AES block cipher
- update feature detection to have meaningful error message

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
~~* [ ] The draft release description has been updated~~
~~* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~~

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
cc @bencrts

**Comment by bencrts** [comment]
@IceTDrinker since the changes are slightly different to what we did on the call -- do you want me to test this on my side?

**Comment by IceTDrinker** [comment]
> @IceTDrinker since the changes are slightly different to what we did on the call -- do you want me to test this on my side?

sure if you have some time to test it would be awesome 👍  we don't yet have M1 instances in the cloud I think

**Comment by bencrts** [comment]
It seems to work!

**Review by agnesLeroy — APPROVED** [review]

**Comment by IceTDrinker** [comment]
I think we can merge this, the failure is a flaky test about CSPRNG uniformity, got an issue for this here : https://github.com/zama-ai/concrete-core-internal/issues/175

**Pull request merged**
