### PR TITLE
chore(ci): add frozen toolchain installation for xtask in GPU workflows

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Description

Add the installation of the frozen toolchain required for xtask calls

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@slab-ci gpu_test

**Review by soonum — APPROVED** [review]
Thanks for the quick fix @IceTDrinker .
Glad it was just a missing step in the workflow.

**Comment by IceTDrinker** [comment]
The worst part is I'm sure I thought about it, and then got caught up in the rustup thing which might have made me want to go faster so that it did not break everyone's workflow

**Comment by IceTDrinker** [comment]
Clippy went through in the GPU builds, I cancelled them and I'll merge this to fix all GPU builds

**Pull request merged**
