### PR TITLE
Feature/views and fixtures

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Resolves:

closes zama-ai/concrete-core-internal#3

### Description

Supersedes https://github.com/zama-ai/concrete/pull/261

- Added so called "views" for LweCiphertext and GlweCiphertext, which are built from slices, this will allow to use memory not allocated in rust if needed (through a C API for example where the caller has already allocated buffers in its own program).
- Views come in two flavors: View and MutView, as &[T] and &mut[T] are two different types in rust
- Creation and retrieval engines were created.
- Retrieval engines consume the entity (otherwise managing memory becomes complicated) and yield the underlying slice back.
- Prototypes for views contain the raw parts of the ciphertext (i.e. the vector from which the slice was taken and the polynomial size as well for GLWE ciphertexts) and not the view itself to ease memory management as well

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)
* [x] The draft release description has been updated
* [x] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
updated the PR with a missed renamed in doc comments

**Comment by IceTDrinker** [comment]
Should not be merged before #1 and a proper rebase on the fresh main that will result from the split

**Comment by IceTDrinker** [comment]
Updated PR to fix a broken doc link that are detected with the updated split repositories branch

**Comment by IceTDrinker** [comment]
rebased on split main

**Comment by IceTDrinker** [comment]
AWS tests have passed, doc is fixed 🙂

**Review by aPere3 — APPROVED** [review]

**Pull request merged**
