### PR TITLE
chore(crates): change the way to declare deps to be git friendly

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Description

- we use multiple location dep declaration, path is used for local builds
or for builds using the git repo
- the version is used for crates published on crates.io

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by IceTDrinker** [comment]
@slab-ci gpu_test

**Review by agnesLeroy — APPROVED** [review]
Looks good to me, anyway we'll be moving concrete-commons inside concrete-core shortly. Then it'll mean we have to bump concrete-npe version between crates.io pushes when there are changes to it we need in concrete-core.

**Comment by agnesLeroy** [comment]
@aPere3 I'm assigning you as reviewer as well, since we've been through this so many times :sweat_smile:

**Comment by IceTDrinker** [comment]
It seems to be working for Mayeul's use case, and it is apparently a common pattern in the rust projects that are multicrates.

Relevant infos from the docs :

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

```
It is possible to specify both a registry version and a git or path location. The git or path dependency will be used locally (in which case the version is checked against the local copy), and when published to a registry like crates.io, it will use the registry version. Other combinations are not allowed.
```

**Pull request merged**
