### PR TITLE
feat(core): add a parallel fft engine to execute PBS in parallel on CPU

### PR DESCRIPTION
**Pull request by agnesLeroy**
### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by agnesLeroy** [comment]
@IceTDrinker @aPere3 I created this branch to benchmark PBS execution over arrays of inputs using multithreading to compare with the GPU implementation. Do you think it'd make sense to merge it?

**Comment by IceTDrinker** [comment]
I don't see why not, as core is now a sort of legacy lib/testing framework for the GPU at the moment

**Comment by aPere3** [comment]
Yep, that make sense to me ! At least, we have a parallel implementation of the PBS that we can play with / use to compare other impls.

**Comment by agnesLeroy** [comment]
@slab-ci cpu_test

**Review by sarah-ek — APPROVED** [review]

**Pull request merged**
