### PR TITLE
fix(ci): fix workflow file format and concurrency for aws gpu tests

### PR DESCRIPTION
**Pull request by soonum**
### Description

Some under indented sections made that workflow impossible to be remotely triggered.

Also the concurrency group name has been enhanced to be able to run GPU and CPU in parallel. Now only a run with the git ref and the same AWS AMI would cancel any previous on-going run.

### Checklist 

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
~~* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
~~* [ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~~
~~* [ ] The draft release description has been updated~~
* [x] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Review by agnesLeroy — COMMENTED** [review]
Hi @soonum! Thanks a lot: does it mean that when triggering GPU tests we always have to specify the instance?

**Comment by soonum** [comment]
No need to. In fact a default configuration is set in Slab config file, this is the same than what's used now with the label.
The concurrency naming change comes handy only when CPU and GPU are running at the same time AND if you want to launch two(or more) GPU tests suite but using different AMIs.

That said I should maybe add the EC2 product type to that naming since it's most likely this parameter one wants to change to test different hardware configuration.

**Comment by soonum** [comment]
Wait before merging @agnesLeroy , I have to fix workflow steps before that.

**Comment by agnesLeroy** [comment]
@soonum is it good now?

**Comment by soonum** [comment]
It seems so, I just wait on Action results for GPU in my test PR.

**Comment by agnesLeroy** [comment]
Let me know when it's ok, I'll approve and merge :)

**Review by agnesLeroy — APPROVED** [review]

**Pull request merged**
