### PR TITLE
Refactor/private cbs vp fixes

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Description

some size checks made no sense in the private API (but we don't currently trigger them in tests, we have an issue for that : https://github.com/zama-ai/concrete-core-internal/issues/414)

use the boolean terminology when referring to ciphertexts containing 1 bit of message (vs binary before) for the cbs primitive

### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Review by agnesLeroy — COMMENTED** [review]
Any reason why you placed boolean as a prefix? In the public API I was thinking we would place it as a suffix instead :thinking:

**Comment by IceTDrinker** [comment]
suffix naming

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Review by agnesLeroy — APPROVED** [review]

**Pull request merged**
