### PR TITLE
feat(cuda): implement lwe ciphertext / plaintext addition in concrete-cuda

### PR DESCRIPTION
**Pull request by agnesLeroy**
### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by agnesLeroy** [comment]
@slab-ci cpu_test

**Comment by agnesLeroy** [comment]
@slab-ci gpu_test

**Comment by pdroalves** [comment]
@agnesLeroy Looks good to me. I just missed the doc tests. Don't we need those anymore?

**Comment by agnesLeroy** [comment]
> @agnesLeroy Looks good to me. I just missed the doc tests. Don't we need those anymore?

I'm not putting them anymore since the public API of Concrete-core is not meant to be maintained anymore (?). They're long to write so I just went for the fast solution. :slightly_smiling_face:

**Comment by agnesLeroy** [comment]
@slab-ci gpu_test

**Pull request merged**
