### PR TITLE
Fix/increase overflow

### PR DESCRIPTION
**Pull request by IceTDrinker**
### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [ ] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [ ] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [ ] The draft release description has been updated
* [ ] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Review by agnesLeroy — APPROVED** [review]

**Comment by IceTDrinker** [comment]
so this is a genuine potential bug, turns out the cause of the bug I caught is overflows but in the forking methods :|

What do you think about switching some of those usize variables to plain u64 ?

**Comment by agnesLeroy** [comment]
> so this is a genuine potential bug, turns out the cause of the bug I caught is overflows but in the forking methods :|
> 
> What do you think about switching some of those usize variables to plain u64 ?

I thought it wouldn't work on 32 bits platforms, hence why we had used usize everywhere :thinking:

**Comment by IceTDrinker** [comment]
> > so this is a genuine potential bug, turns out the cause of the bug I caught is overflows but in the forking methods :|
> > What do you think about switching some of those usize variables to plain u64 ?
> 
> I thought it wouldn't work on 32 bits platforms, hence why we had used usize everywhere 🤔

Ah well, wasm is a 32 bits platform at the moment 😬

**Comment by IceTDrinker** [comment]
I'll avoid using forking in wasm32 for now, it's a feature mainly to have reproducible multi/mono threaded keygens anyways

**Comment by agnesLeroy** [comment]
Alright, then I'll merge this one, but we should take care of overflows in the forking at some point.

**Pull request merged**
