### PR TITLE
fix(cuda): fix checks in Cuda backend

### PR DESCRIPTION
**Pull request by agnesLeroy**
### Checklist 

(Use '[x]' to check the checkboxes, or submit the PR and then click the checkboxes)

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The PR description links to the related issue (to link an issue, use '#XXX'.)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] The draft release description has been updated
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

### CODE REVIEW

**Comment by agnesLeroy** [comment]
@slab-ci gpu_test

**Review by pdroalves — CHANGES_REQUESTED** [review]
Hey @agnesLeroy !
This PR looks like to me. We just need to fix that "Rustfmt and Clippy check" issue.

**Comment by agnesLeroy** [comment]
> Hey @agnesLeroy ! This PR looks like to me. We just need to fix that "Rustfmt and Clippy check" issue.

Should be fixed now :slightly_smiling_face: May I let you approve so I can merge? Thansk :slightly_smiling_face:

**Review by pdroalves — APPROVED** [review]

**Comment by pdroalves** [comment]
Do you think we need to rerun the tests?
I had a green flag before the last push and I don't see anything new that could break them.

**Comment by agnesLeroy** [comment]
@pdroalves no need to, the failing test on CPU is a flaky one

**Pull request merged**
