### PR TITLE
feat(concrete-fft): add concrete-fft backend

### PR DESCRIPTION
**Pull request by sarah-ek**
### Description
this PR intergrates a new pure rust fft backend. right now the dependency points to the concrete-fft github repo. but this should be changed to a crates.io version once the crate is published.

### Checklist 

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [x] The tests on AWS have been launched and are successful (comment with @slab-ci cpu_test and/or @slab-ci gpu_test to trigger the tests)
* [x] Check for breaking changes (including serialization changes) and add them to commit message following the conventional commit [specification][conventional-breaking]

### CODE REVIEW

**Comment by agnesLeroy** [comment]
@sarah-ek let's wait for the concrete-fft repository to go public and for the crate to be pushed to crates.io: otherwise we can't verify the CI is passing.

**Comment by agnesLeroy** [comment]
@sarah-ek your message commit doesn't comply with the convention we check for, you can use this instead:
```
feat(core): ...
```

**Review by agnesLeroy — APPROVED** [review]

**Comment by IceTDrinker** [comment]
@slab-ci cpu_test

**Comment by agnesLeroy** [comment]
@sarah-ek do yo uhave an idea what's causing the build error?

**Comment by agnesLeroy** [comment]
@sarah-ek for what you can do is use the compilation flag `__ci_do_not_compile` to remove that feature when `--all-features` is used. This is what's used for the Cuda support in the CI. Then you'll have to add a task for the nightly feature (in concrete-tasks and in the workflow file for slab) -> we don't use the labels to trigger workflows so only updating the slab workflow should be good.

**Comment by sarah-ek** [comment]
this might be an issue because `backend_fft_nightly_avx512` also enables nightly features in `concrete-fft`. i don't think we can have a feature that disables that since cargo expects features to be additive.

would it be possible to add an `__all_stable_features` feature that enables all stable features, and change the CI from using `--all-features` to something like `--features=__al_stablel_features`?

**Comment by IceTDrinker** [comment]
feature handling will change with the aarch64 PR, I think it's fine to have a band aid fix for now and we'll manage it properly with the addition of the aarch64 macs support, wdyt ?

**Comment by sarah-ek** [comment]
for now i commented out the simd features. we can enable them again once we have figured out a solution for the CI

**Comment by agnesLeroy** [comment]
@slab-ci cpu_test

**Pull request merged**
